#!/bin/bash
# Common stuff shared by railsbuild scripts

RAILSBUILD_VERSION=0.3

# Fedora master branch
FEDORA_RAWHIDE=23

# Ruby on Rails gems
GEMS=(activesupport
      activejob
      activemodel
      activerecord
      actionview
      actionpack
      actionmailer
      railties
      rails)

# Gems that needs to be rebuild without bootstrapping
BOOTSTRAPPED_GEMS=(actionview
                   actionpack)
