#!/usr/bin/bash
# Run Rails build of new packages. For every package run scratch-build
# first and if that succeeds, push changes and run the final build.
#
# Done builds are marked by .build in the repository, so running
# this script after it failed will pick up the work from the last run.
#
# Usage:
#   ./railsbuild-build FEDORA_VERSION VERSION

. $(dirname $(readlink -f "$0"))/railsbuild-common

FEDORA_VERSION=$1
VERSION=$2

for gem in "${GEMS[@]}"
do
  pushd ~/.railsbuild/f$FEDORA_VERSION/rubygem-$gem
    # Skip already done builds
    if [ -f .built ]; then
      echo "$gem: build for $gem already done"
      continue
    fi

    rm *.src.rpm
    fedpkg scratch-build --srpm

    if [ "$?" = "0" ]; then
      touch .scratch-built
      git stash
      echo "= SUCCESS ======"
      echo "$gem: scratch build of rubygem-$gem succeeded"
      fedpkg import rubygem-$gem-*.src.rpm > /dev/null

      if [ ! "$?" = "0" ]; then
        echo "= FAIL ======"
        echo "$gem: fedpkg import failed"
        exit 1
      fi

      git commit -am "Update to $gem $VERSION"
      git push
      fedpkg build
      
      if [ "$?" = "0" ]; then
        echo "= SUCCESS ======"
        echo "$gem: build of rubygem-$gem succeeded"
        echo "$gem: waiting until the build becomes available..."
        koji wait-repo f$FEDORA_VERSION-build --build=rubygem-$gem-$VERSION-1.fc$FEDORA_VERSION
        touch .built
      else
        echo "= FAIL ======"
        echo "$gem: build of rubygem-$gem failed"
        exit 1
      fi
    else
      echo "= FAIL ======"
      echo "$gem: scratch-build of rubygem-$gem failed"
      exit 1
    fi

  popd
done

echo
echo
echo "= SUCCESSFULLY DONE ====="
echo "Build of Ruby on Rails $VERSION for Fedora release $FEDORA_VERSION done."
echo 
echo "Run the following to delete the build metadata:" 
echo "  rm ~/.railsbuild/f$FEDORA_VERSION/rubygem-*/.*built"
